version: "3"

services:
  auth-service:
    build: ./services/auth-service
    ports:
      - "3001:3001"

  user-service:
    build: ./services/user-service
    ports:
      - "3002:3002"

  order-service:
    build: ./services/order-service
    ports:
      - "3003:3003"
    env_file:
      - ./services/order-service/.env


  notification-service:
    build: ./services/notification-service
    ports:
      - "3004:3004"
    env_file:
      - ./services/notification-service/.env