apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
spec:
  replicas: {{ .Values.order.replicaCount}}
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
      - name: order-service
        image: {{ .Values.order.image }}
        imagePullPolicy: Never
        ports:
        - containerPort: 3003
        env:
        - name: AWS_ACCESS_KEY
          value: {{ .Values.aws.accessKey}}
        - name: AWS_SECRET_KEY
          value: {{ .Values.aws.secretKey }}
        - name: AWS_REGION
          value: {{ .Values.aws.region }}
        - name: SQS_URL
          value: {{ .Values.aws.sqsUrl }}